/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiBriefRouteImport } from './routes/api/brief'
import { Route as ApiBriefFileRouteImport } from './routes/api/brief-file'
import { Route as ApiBriefFinaliseRouteImport } from './routes/api/brief-finalise'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiNotifyRetryRouteImport } from './routes/api/notify-retry'
import { Route as ApiStudioFileFileIdRouteImport } from './routes/api/studio-file.$fileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefRoute = ApiBriefRouteImport.update({
  id: '/api/brief',
  path: '/api/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefFileRoute = ApiBriefFileRouteImport.update({
  id: '/api/brief-file',
  path: '/api/brief-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefFinaliseRoute = ApiBriefFinaliseRouteImport.update({
  id: '/api/brief-finalise',
  path: '/api/brief-finalise',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyRetryRoute = ApiNotifyRetryRouteImport.update({
  id: '/api/notify-retry',
  path: '/api/notify-retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioFileFileIdRoute = ApiStudioFileFileIdRouteImport.update({
  id: '/api/studio-file/$fileId',
  path: '/api/studio-file/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/brief-file': typeof ApiBriefFileRoute
  '/api/brief-finalise': typeof ApiBriefFinaliseRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify-retry': typeof ApiNotifyRetryRoute
  '/api/studio-file/$fileId': typeof ApiStudioFileFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/brief-file': typeof ApiBriefFileRoute
  '/api/brief-finalise': typeof ApiBriefFinaliseRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify-retry': typeof ApiNotifyRetryRoute
  '/api/studio-file/$fileId': typeof ApiStudioFileFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/brief-file': typeof ApiBriefFileRoute
  '/api/brief-finalise': typeof ApiBriefFinaliseRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notify-retry': typeof ApiNotifyRetryRoute
  '/api/studio-file/$fileId': typeof ApiStudioFileFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/api/brief'
    | '/api/brief-file'
    | '/api/brief-finalise'
    | '/api/health'
    | '/api/notify-retry'
    | '/api/studio-file/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio'
    | '/api/brief'
    | '/api/brief-file'
    | '/api/brief-finalise'
    | '/api/health'
    | '/api/notify-retry'
    | '/api/studio-file/$fileId'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/api/brief'
    | '/api/brief-file'
    | '/api/brief-finalise'
    | '/api/health'
    | '/api/notify-retry'
    | '/api/studio-file/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRoute: typeof StudioRoute
  ApiBriefRoute: typeof ApiBriefRoute
  ApiBriefFileRoute: typeof ApiBriefFileRoute
  ApiBriefFinaliseRoute: typeof ApiBriefFinaliseRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNotifyRetryRoute: typeof ApiNotifyRetryRoute
  ApiStudioFileFileIdRoute: typeof ApiStudioFileFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief': {
      id: '/api/brief'
      path: '/api/brief'
      fullPath: '/api/brief'
      preLoaderRoute: typeof ApiBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief-file': {
      id: '/api/brief-file'
      path: '/api/brief-file'
      fullPath: '/api/brief-file'
      preLoaderRoute: typeof ApiBriefFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief-finalise': {
      id: '/api/brief-finalise'
      path: '/api/brief-finalise'
      fullPath: '/api/brief-finalise'
      preLoaderRoute: typeof ApiBriefFinaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-retry': {
      id: '/api/notify-retry'
      path: '/api/notify-retry'
      fullPath: '/api/notify-retry'
      preLoaderRoute: typeof ApiNotifyRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio-file/$fileId': {
      id: '/api/studio-file/$fileId'
      path: '/api/studio-file/$fileId'
      fullPath: '/api/studio-file/$fileId'
      preLoaderRoute: typeof ApiStudioFileFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRoute: StudioRoute,
  ApiBriefRoute: ApiBriefRoute,
  ApiBriefFileRoute: ApiBriefFileRoute,
  ApiBriefFinaliseRoute: ApiBriefFinaliseRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNotifyRetryRoute: ApiNotifyRetryRoute,
  ApiStudioFileFileIdRoute: ApiStudioFileFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
